// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5163/' | (string & {});
};

export type AddBoxDto = {
    name: string;
    groupId?: null | string;
};

export type AddCardDto = {
    setCode: null | string;
    setNumber: null | string;
    name: null | string;
    condition: string;
    foilType?: string;
    stampType?: string;
    language?: string;
    isProxy?: boolean;
    isSigned?: boolean;
    alterArtist?: null | string;
    notes?: null | string;
    boxId?: null | string;
    acquiredDate?: null | string;
    purchasePrice?: null | number | string;
};

export type AddEntityDto = {
    name: string;
    type?: string;
    location?: null | string;
};

export type AddGroupDto = {
    name: string;
    description?: null | string;
    entityId?: null | string;
    parentGroupId?: null | string;
};

export type UpdateBoxDto = {
    name: null | string;
    groupId: null | string;
};

export type UpdateCardDto = {
    setCode: null | string;
    setNumber: null | string;
    name: null | string;
    condition: null | string;
    foilType: null | string;
    stampType: null | string;
    language: null | string;
    isProxy: null | boolean;
    isSigned: null | boolean;
    alterArtist: null | string;
    notes: null | string;
    boxId: null | string;
    acquiredDate: null | string;
    purchasePrice: null | number | string;
};

export type UpdateEntityDto = {
    name: null | string;
    type: null | string;
    location: null | string;
};

export type UpdateGroupDto = {
    name: null | string;
    description: null | string;
    entityId: null | string;
    parentGroupId: null | string;
};

export type GetApiBoxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/boxes';
};

export type GetApiBoxesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBoxesData = {
    body: AddBoxDto;
    path?: never;
    query?: never;
    url: '/api/boxes';
};

export type PostApiBoxesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiBoxesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/boxes/{id}';
};

export type DeleteApiBoxesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBoxesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/boxes/{id}';
};

export type GetApiBoxesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBoxesByIdData = {
    body: UpdateBoxDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/boxes/{id}';
};

export type PutApiBoxesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBoxesByGroupByGroupIdData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/boxes/by-group/{groupId}';
};

export type GetApiBoxesByGroupByGroupIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cards';
};

export type GetApiCardsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiCardsData = {
    body: AddCardDto;
    path?: never;
    query?: never;
    url: '/api/cards';
};

export type PostApiCardsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiCardsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cards/{id}';
};

export type DeleteApiCardsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCardsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cards/{id}';
};

export type GetApiCardsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiCardsByIdData = {
    body: UpdateCardDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cards/{id}';
};

export type PutApiCardsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiEntitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/entities';
};

export type GetApiEntitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiEntitiesData = {
    body: AddEntityDto;
    path?: never;
    query?: never;
    url: '/api/entities';
};

export type PostApiEntitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiEntitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/entities/{id}';
};

export type DeleteApiEntitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiEntitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/entities/{id}';
};

export type GetApiEntitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiEntitiesByIdData = {
    body: UpdateEntityDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/entities/{id}';
};

export type PutApiEntitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type GetApiGroupsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiGroupsData = {
    body: AddGroupDto;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type PostApiGroupsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiGroupsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type DeleteApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type GetApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiGroupsByIdData = {
    body: UpdateGroupDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type PutApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsByEntityByEntityIdData = {
    body?: never;
    path: {
        entityId: string;
    };
    query?: never;
    url: '/api/groups/by-entity/{entityId}';
};

export type GetApiGroupsByEntityByEntityIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsByParentByParentIdData = {
    body?: never;
    path: {
        parentId: string;
    };
    query?: never;
    url: '/api/groups/by-parent/{parentId}';
};

export type GetApiGroupsByParentByParentIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
