"""initial schema with entity

Revision ID: a0807215042a
Revises: 
Create Date: 2026-07-02 18:37:54.294617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0807215042a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('personal', 'club', 'friend', 'shop', name='entitytype'), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cardinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sa.Enum('near_mint', 'lightly_played', 'moderately_played', 'heavily_played', 'damaged', name='condition'), nullable=False),
    sa.Column('foil_type', sa.Enum('none', 'traditional', 'pre_modern', 'from_the_vault', 'etched', 'textured', 'fracture', 'double_rainbow', 'confetti', 'galaxy', 'gilded', 'halo', 'invisible_ink', 'neon_ink', 'oil_slick', 'silverscreen', 'step_and_compleat', 'surge', name='foiltype'), nullable=False),
    sa.Column('stamp_type', sa.Enum('none', 'promo', 'prerelease', name='stamptype'), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardinstance')
    op.drop_table('storage')
    op.drop_table('collection')
    op.drop_table('entity')
    # ### end Alembic commands ###
